# Generated by Django 6.0.5 on 2026-06-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_produto_imagem_produto_imagem_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='imagem_url',
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
    ]
