# Generated by Django 6.0.5 on 2026-06-13 02:38

from decimal import Decimal

from django.db import migrations, models


def marcar_promocoes_iniciais(apps, schema_editor):
    Produto = apps.get_model("core", "Produto")
    promocoes = {
        "Mouse Gamer Sem Fio Logitech G PRO X SUPERLIGHT": "1058.81",
        "Teclado Gamer Razer Huntsman V3 Pro Mini": "1799.89",
        "Razer BlackWidow V3 Tenkeyless TKL": "1541.16",
        "Teclado Gamer Logitech G PRO X TKL": "1764.69",
        "Teclado Mecânico Gamer Sem Fio Logitech G715 LIGHTSPEED": "1363.62",
        "Teclado Mecânico Gamer HyperX Alloy Origins Core": "1058.81",
        "Headset Sem Fio Gamer Razer Blackshark V3 Pro": "2624.43",
        "Headset Gamer Sem Fio Logitech G325 LIGHTSPEED": "823.42",
        "Headset Gamer Sem Fio Logitech G435, Lightspeed e Bluetooth": "952.93",
        "Controle Sony DualSense PS5": "461.29",
        "Resident Evil Requiem": "299.00",
        "DEATH STRANDING 2: ON THE BEACH": "399.90",
    }

    for nome, valor_antigo in promocoes.items():
        Produto.objects.filter(nome=nome).update(
            em_promocao=True,
            valor_antigo=Decimal(valor_antigo),
        )


def desmarcar_promocoes_iniciais(apps, schema_editor):
    Produto = apps.get_model("core", "Produto")
    Produto.objects.update(em_promocao=False, valor_antigo=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_produto_imagem_url_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='em_promocao',
            field=models.BooleanField(default=False, verbose_name='Em promocao'),
        ),
        migrations.AddField(
            model_name='produto',
            name='valor_antigo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor antigo'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=150, verbose_name='Nome'),
        ),
        migrations.RunPython(marcar_promocoes_iniciais, desmarcar_promocoes_iniciais),
    ]
